### ISSUE TITLE
YAML file for epadmin create

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.5#24]
Allow a YAML file with configuration to be used to create a new archive rather than having to use the guided interface.

**Comment by fatchild** [comment]
Notes from test
- YAML::Tiny not installed
`Failed to create repository using config file: /opt/eprints3/testdata/data/ejo35_archive_config.yml. YAML::Tiny is not installed.`
- Database password suggested despite me setting one in the YAML file, password  contained an & symbol
- Create user failed for mysql
`DBD::mysql::db do failed: Operation CREATE USER failed for 'eprints'@'localhost' at /opt/eprints3/perl_lib/EPrints/Database/mysql.pm line 163.`

My create file...
```
flavour: 'pub'
archive_id: 'ejo35'
core:
  host: 'ejo1f20-35.eprints-hosting.org'
  port: 80
  aliases: []
  path: '/'
  securehost: 'ejo1f20-35.eprints-hosting.org'
  secureport: 443
  adminemail: 'ejo1f20@soton.ac.uk'
  phrases:
    archive_name: 'Eds 3.5 Test Repo'
    organisation_name: 'Eds org'
database:
  dbname: 'ejo35'
  dbhost: 'localhost'
  dbport: '#'
  dbsock: '#'
  dbuser: 'eprints'
  dbpass: 'HIDDEN'
  dbengine: 'InnoDB'
  dbcharset: 'utf8mb4'
  admin:
    username: 'eprints'
    password: 'eprints'
user:
  username: 'admin'
  usertype: 'admin'
  password: 'HIDDEN'
  email: 'ejo1f20-35.eprints-hosting.org'
generate_static: 'yes'
import_subjects: 'yes'
generate_apacheconf: 'yes'
```
