### ISSUE TITLE
Versioning for flavours, ingredients, etc.

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.5#42]
Anything that gets added to includes for an archive's package.yml file should have a version number and this should be checked that it meets the requirements on version specified by package.yml.  This is probably best acheived with another YAML file.  I propose this be called info.yml and sit in the top level of the flavour, ingredient or whatever.  Reusing the metadata that is already used on `flavour_info.pl`. This contains:
1. id
2. name
3. version
4. version alias

I think version aliases should be abandoned even for flavours. However, it may be useful to have some additional metadata:

- type - `flavour`, `ingredient` or `library`.  At the moment probably the only thing that would be checked is that there is no more than one flavour for an archive.  Library could cover things like site_lib.  Really it is just to indicate it provides various than specific functionality and in essence means other (i.e. neither a flavour nor and ingredient).
- maintainers -  Should contain name and ideally email address as well
- description - Should give a description of the included directory
- requires - Dependencies to check for in the includes of the archive package.yml file.
- notes - Installation instructions, general advice, etc.

```
id: "pub_flavour"
name: "Research Publications Flavour"
type: "flavour"
version: 2.0
maintainers: 
  - name: "David Newman"
    email: "drn@example.org"
  - name: "Ed Oakley"
    email "ejo@example.org"
description: "This is a flavour that makes EPrints into a research publications repository."
requires:
notes: "This can be installed bu just dropping it into the flavours sub-directory."
```
