### ISSUE TITLE
Use CSS to control columns for browse views

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.5#5]
Some browse views result in very long menu pages.
If the view config uses `new_column_at` then the resulting rendering uses tables to lay out the multiple columns:
https://github.com/eprints/eprints3.4/blob/master/perl_lib/EPrints/Update/Views.pm#L1523-L1534 

With more recent CSS, this layout can be achieved in a fairly simple manner, using a 'column' rule similar to this:
```css
/* direct ancestor here avoids impacting menus that are still using the eprints-generated columns */
.ep_view_menu > ul {
  -webkit-columns: 200px 4; /* 200px is the min width of a column; 4 is the max number of columns to split into */
  -moz-columns: 200px 4;
  columns: 200px 4;
  -webkit-column-gap: 10;
  -moz-column-gap: 10;
  column-gap: 10;
}
```

A rule such as the above could be used without modifying core code - just advice on removing the `new_column_at` setting for menus, so that the links are rendered into a single `<ul>`.

The `columns` CSS appears to be well supported: https://caniuse.com/?search=columns 

Here is a demonstration : https://codepen.io/jesusbagpuss/pen/BarYRwy - which also includes a JQuery 'filter' option.

With the default table-based layout this filter results in poor user experience as the columns can end up very uneven.
Using the CSS approach the columns are automatically equalised.
